# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bismillah

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: set -e
      - run: npm install -g @vue/cli
      - run: rm -rf node_modules/
      - run: npm install
      - run: npm run build

      - name: Diste Gec
        working-directory: dist
        run: |
          echo 'mukabele.hayrat.dev' > CNAME
          git init
          git add -A
          git config --global user.email "sametileri07@gmail.com"
          git config --global user.name "Abdulsamet İleri"
          git commit -m 'deploy'

      - name: Pushla
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
          directory: dist
          force: true

        env:
          CI: true
